### ISSUE TITLE
Test results on dataset CUHK-PEDES

### ISSUE THREAD

**Issue by InstantWindy** [Flame-Chasers/TBPS-CLIP#1]
I used the s.config.yaml file (Only the batch_size value was changed to 40) to train the CUHK-PEDES dataset and the test results are as follows:
![image](https://github.com/Flame-Chasers/TBPS-CLIP/assets/23608180/6346b9d9-2530-472c-9834-245e331202b5)

The result differs from that in the paper

**Comment by byougert** [comment]
Hi @InstantWindy ,

Thank you for sharing your results and the details about your training setup.

TBPS-CLIP is built on the foundation model CLIP that aligns images and texts by contrastive learning. Typically, negative samples are selected from the same batch. However, with the **decrease of batch size**, the scope of the contrasted negative samples will be narrowed. 

Specifically, we trained the model with a batch_size_per_gpu of 80 on 4 GPUs, which means the total batch size is 320. However, according to the screenshot you provided with a dataloader length of 567, it seems you trained the model with a batch_size_per_gpu of 40 on 3 GPUs. Relatively, the batch size has sharply shrinked.

Additionally, we would like to share the experimental results we obtained using a batch_size_per_gpu of 40 on 4 GPUs:
- Acc@1: 71.21507
- Acc@5: 87.76803
- Acc@10: 92.18649
- mAP: 63.84590

These results provide insights into the model's performance under the specific batch size configuration we used.
