### ISSUE TITLE
I don't have 4 GPU A40. But i only have 1 A100 on my school server. How can i train this model with only 1 GPU@@. Please help

### ISSUE THREAD

**Issue by dukeNG2012** [Flame-Chasers/TBPS-CLIP#2]

**Comment by byougert** [comment]
Hi @dukeNG2012 ,

You can set nproc_per_node=1 at [here](https://github.com/Flame-Chasers/TBPS-CLIP/blob/master/shell/train.sh#L3).

**Comment by dukeNG2012** [comment]
@byougert thank you for your help
