### ISSUE TITLE
Model checkpoint

### ISSUE THREAD

**Issue by AtiChetsurakul** [Flame-Chasers/TBPS-CLIP#4]
Since I have not enough resource to train this model for my internal comparison in my thesis. Will there be any chance, that you might release a trained model checkpoint? 
If no, it is ok. Thank you for release a good work.

**Comment by byougert** [comment]
Hi @AtiChetsurakul ,
Thx for your interest in our work.

We have released the model checkpoints for the TBPS-CLIP project. You can find them [here](https://github.com/Flame-Chasers/TBPS-CLIP/tree/master?tab=readme-ov-file#model-checkpoints) on the three TBPS benchmarks.

If you have any further questions or need additional assistance, please feel free to ask.

**Comment by AtiChetsurakul** [comment]
thx
