### ISSUE TITLE
Problem consultation

### ISSUE THREAD

**Issue by 1028Bjt** [Flame-Chasers/TBPS-CLIP#5]
Excuse me, I saw in your article that you mentioned optimizing loss in CLIP. As a novice, I would like to ask where the specific code snippet is? Looking forward to your reply. Best wishes

**Comment by byougert** [comment]
Hi @1028Bjt , thanks for your interest in our work.
Please refer to [here](https://github.com/Flame-Chasers/TBPS-CLIP/blob/6160a877af99229bbf39077b1047d96cf7fda64c/model/tbps_model.py#L120) for the loss designing.
